version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres-test
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
