<?php

namespace ContainerOEUepja;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculatePriceRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Request\CalculatePriceRequest' shared autowired service.
     *
     * @return \App\Request\CalculatePriceRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Request/BaseRequest.php';
        include_once \dirname(__DIR__, 4).'/src/Request/CalculatePriceRequest.php';

        return $container->privates['App\\Request\\CalculatePriceRequest'] = new \App\Request\CalculatePriceRequest(($container->privates['validator'] ?? self::getValidatorService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
