<?php

namespace ContainerXSDDnSG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LKHq1MNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lKHq1MN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lKHq1MN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'request' => ['privates', '.errored.8wvp32K', NULL, 'Cannot determine controller argument for "App\\Controller\\ProductController::calculatePrice()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProductPriceRequest". Did you forget to add a use statement?'],
            'service' => ['privates', 'App\\Service\\ProductService', 'getProductServiceService', true],
        ], [
            'em' => '?',
            'request' => '?',
            'service' => 'App\\Service\\ProductService',
        ]);
    }
}
