<?php

namespace ContainerXSDDnSG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_8wvp32KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.8wvp32K' shared service.
     *
     * @return \App\Controller\ProductPriceRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ProductController::calculatePrice()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProductPriceRequest". Did you forget to add a use statement?');
    }
}
