<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOEUepja\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOEUepja/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOEUepja.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOEUepja\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOEUepja\App_KernelDevDebugContainer([
    'container.build_hash' => 'OEUepja',
    'container.build_id' => '621ef37a',
    'container.build_time' => 1697435254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOEUepja');
