<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_default_root' => [[], ['_controller' => 'App\\Controller\\DefaultController::root'], [], [['text', '/']], [], [], []],
    'app_product_calculateprice' => [[], ['_controller' => 'App\\Controller\\ProductController::calculatePrice'], [], [['text', '/api/v1/product/calculate']], [], [], []],
];
